services:
  - type: web
    name: fm-radio
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn fm_station.wsgi:application
